---
- name: "Sets the website to {{ state }}"
  hosts: localhost
  connection: local
  vars:
  ##############################################################
    state: stopped   #  <--- FILL IN 'started' or 'stopped'    #
  ##############################################################
  tasks:
    - name: Install/uninstall packages
      ansible.builtin.package:
        name: 
          - apache2
          - rsync # needed for later ansible task
        state: "{{ absent_or_present[state] }}"
      become: true
      vars:
        absent_or_present:
          stopped: absent
          started: present

    - name: 
      ansible.builtin.systemd:
        name: apache2
        state: "{{ state }}"
        enabled: "{{ enabled_mapping[state] }}"
      become: true
      vars:
        enabled_mapping:
          started: true
          stopped: false
    
    - name: Ensure default site is disabled
      ansible.builtin.shell: a2dissite 000-default.conf
      become: true
      when: state == 'started'
    
    - name: Ensure /var/www/html is empty
      ansible.builtin.file:
        name: "/var/www/html"
        state: "{{ item }}"
        owner: root
        group: root
      loop:
        - absent
        - directory
      become: true
    
    - name: Ensure /var/www/html contains website
      ansible.builtin.synchronize:
        src: "my_website/"
        dest: "/var/www/html/"
        recursive: true
      become: true
      when: state == 'started'